spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: admin
      password: js!151515
    url: jdbc:mysql://groaddb.c2scr40vcnhr.ap-northeast-1.rds.amazonaws.com?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true&useSSL=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    database: mysql
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate:
      type: debug
      sql: debug
    org.springframework: debug

server:
  port: 9191